import Fibonacci._
import org.scalatest._
import flatspec._
import matchers._

class FibonacciSpec extends AnyFlatSpec with should.Matchers {

  behavior of "Fibonacci.fibonacciSequence()"

  "fibonacciSequence, when h > 100" should "be generated by adding the previous two terms in sequence" in {
    fibonacci(10) shouldBe 55
    fibonacci(5) shouldBe 5
  }

}