import Fibonacci._
import org.scalatest._
import flatspec._
import matchers._

class FibonacciSpec extends AnyFlatSpec with should.Matchers {

  behavior of "Fibonacci.fibonacciSequence()"

  "fibonacciSequence, when h > 100" should "be generated by adding the previous two terms in sequence" in {
    fibonacciSequence(1, 2) shouldBe List(1, 2, 3, 5, 8, 13, 21, 34, 55, 89)
    fibonacciSequence(4, 5) shouldBe List(4, 5, 9, 14, 23, 37, 60, 97)
  }

}